apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: elastic
  labels:
    app: filebeat
spec:
  ports:
  - port: 80
    name: nginx-port
  selector:
    app: filebeat
  type: NodePort
